# Generated by Django 4.1.4 on 2023-01-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='adb',
        ),
    ]
