# Generated by Django 4.1.4 on 2022-12-30 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
