# Generated by Django 4.1.4 on 2022-12-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_group_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='logs',
        ),
        migrations.AddField(
            model_name='group',
            name='logs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='logs.log'),
        ),
    ]
