# Generated by Django 4.1.4 on 2022-12-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_remove_group_logs_group_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='logs',
        ),
        migrations.AddField(
            model_name='group',
            name='logs',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='logs.log'),
        ),
    ]
