# Generated by Django 4.1.4 on 2022-12-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_remove_group_logs_group_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['date_added'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['date_added'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
