# Generated by Django 4.1.4 on 2023-01-25 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
