# Generated by Django 4.1.7 on 2023-07-18 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_group_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='logs',
        ),
        migrations.AddField(
            model_name='log',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.group'),
        ),
    ]
