# Generated by Django 4.1.4 on 2023-01-11 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_group_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='logs',
        ),
        migrations.AddField(
            model_name='group',
            name='logs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='logs.log'),
            preserve_default=False,
        ),
    ]
