# Generated by Django 4.1.4 on 2023-01-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0015_remove_group_logs_group_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='logs',
        ),
        migrations.AddField(
            model_name='group',
            name='logs',
            field=models.ManyToManyField(related_name='groups', to='logs.log'),
        ),
    ]
