# Generated by Django 4.1.4 on 2023-01-11 23:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0017_log_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
