# Generated by Django 4.1.4 on 2023-01-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0018_alter_log_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.TextField(),
        ),
    ]
