# Generated by Django 4.1.4 on 2023-01-12 21:33

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0019_alter_log_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
