# Generated by Django 4.1.4 on 2023-01-12 22:28

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0020_alter_log_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
