# Generated by Django 4.1.4 on 2023-01-14 12:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0021_alter_log_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
