# Generated by Django 4.1.4 on 2023-01-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0022_alter_log_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
