# Generated by Django 4.1.4 on 2023-01-14 14:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0023_alter_log_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
