MYCONFIG = {
    'default': {
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document',
             'items': ['Templates', ]},
            {'name': 'editing',
             'items': ['Find', ]},
            {'name': 'basicstyles',
             'items': [
                'Bold',
                'Italic',
                'Underline',
                'Strike',
                'Subscript',
                'Superscript',
                '-',
                'RemoveFormat'
                ]},
            {'name': 'paragraph',
             'items': [
                'NumberedList',
                'BulletedList',
                '-',
                'JustifyLeft',
                'JustifyCenter',
                'JustifyRight',
                'JustifyBlock',
                '-',
                ]},
            {'name': 'links',
             'items': ['Link', 'Unlink']},
            {'name': 'insert',
             'items': [
                'Flash',
                'Table',
                'HorizontalRule',
                'Smiley',
                ]},
            '/',
            {'name': 'styles',
             'items': [
                'Styles',
                'Format',
                'Font',
                'FontSize'
                ]},
            {'name': 'colors',
             'items': [
                'TextColor',
                'BGColor',
                'Image',
                'CodeSnippet',
                'Youtube',
                'Preview'
                ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',
        # 'height': '100%',
        'width': '125%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        "removePlugins": "exportpdf",
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'codesnippet',
            'youtube',
        ]),
    },


    'comment': {
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'basicstyles',
             'items': [
                'Smiley',
                'Bold',
                'Italic',
                'Underline',
                'Strike',
                'Subscript',
                'Superscript',
                ]},
            {'name': 'paragraph',
             'items': [
                'NumberedList',
                'BulletedList',
                ]},
            {'name': 'links',
             'items': [
                'Link',
                'Unlink'
                ]},
            {'name': 'colors',
             'items': [
                'TextColor',
                'BGColor',
                'Image',
                'CodeSnippet',
                'Youtube',
                ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',
        'height': '100%',
        'width': '200%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        "removePlugins": "exportpdf",
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'codesnippet',
            'youtube',
        ]),
    }
}
